### PR TITLE
chore(client): update ABIs

### PR DESCRIPTION
**Pull request by harbu**
## Summary

Update ABIs and a small refactoring consolidating all ABIs to a single place.

## Changes

- Update from `StreamRegistryV3` to `StreamRegistryV4`
- Update from `StreamStorageRegistry` to `StreamStorageRegistryV2`
- Consolidate all ABIs under `src/ethereumArtifcats`
  - Remove unused ABI artifact `contracts/NodeRegistry.json`
  - Move `TrackerRegistry` to `src/ethereumArtifacts`.
  - Remove `contracts` directory
  
## Future improvments
- New version of ABI `StreamRegistryV4` would allow us to implement `createMultipleStreamsWithPermissions`, `createStreamWithPermissions`, and `setPermissionsMultipleStreams` in client.

## Checklist before requesting a review

- [x] Is this a breaking change? If it is, be clear in summary.
- [x] Read through code myself one more time.
- [x] Make sure any and all `TODO` comments left behind are meant to be left in.
- [x] Has reasonable passing test coverage?
- [x] Updated changelog if applicable.
- [x] Updated documentation if applicable.

### CODE REVIEW

**Review by teogeb — COMMENTED** [review]
Do need to update the contract address for `StreamStorageRegistry` v2 (`config.schema.json` and `ConfigTest.ts`)?

Could also fix typo on `StreamRegistry.ts:396` (related to v3->v4 update)

**Comment by harbu** [comment]
> Do need to update the contract address for `StreamStorageRegistry` v2 (`config.schema.json` and `ConfigTest.ts`)?

I believe not since `setTrustedForwarder` exists in the current address https://polygonscan.com/address/0xe8e2660cedf2a59c917a5ed05b72df4146b58399#writeProxyContract.

> Could also fix typo on `StreamRegistry.ts:396` (related to v3->v4 update)

<del>Don't know what you are referring to?</del>

<del>Ah you mean the StreamRegistry contract has a spelling mistake `setPermissionsMultipleStreans`. I wonder if we can just change that or does it require a contract update?</del>

Fixed :+1:

**Review by teogeb — APPROVED** [review]

**Comment by harbu** [comment]
Looks like the fixed spelling doesn't work on streamr-docker-dev stack @teogeb , probably will need to revert that and get back to it once the contract in docker is updated?

**Comment by teogeb** [comment]
> Looks like the fixed spelling doesn't work on streamr-docker-dev stack @teogeb , probably will need to revert that and get back to it once the contract in docker is updated?

Or maybe we need to postpone merging of this PR until that is done. As that indicated that docker-dev environment is still using v3. Our test runs aren't valid if we update ABIs to v4 but docker-dev is still in v3.

**Comment by harbu** [comment]
Newest versions of smart contracts now in streamr-docker-dev and tests pass!

**Pull request merged**
