### PR TITLE
Convert cross-client-testing Gradle library to Gradle application

### PR DESCRIPTION
**Pull request by kare**
* Gradle Application provides a distribution and a script to execute client_testing application
* Jar Main-Class is replaced by distribution's executable script

### CODE REVIEW

**Comment by kare** [comment]
@timoxley Merge #29 first, thanks

**Comment by timoxley** [comment]
@kare done

**Comment by timoxley** [comment]
@kare is this still WIP?

**Comment by kare** [comment]
@timoxley It's done

**Pull request merged**
