### PR TITLE
NET-682: fix: pix possible issue with a stream being returned before it was cr…

### PR DESCRIPTION
**Pull request by samt1803**
…eated and synched

### CODE REVIEW

**Review by harbu — APPROVED** [review]
If I understood correctly, the change here is that we poll the graph now also in non-ens domain cases. LGTM; @teogeb do you want to have a look as well, since you may be aware of any subtleties as I'm not as familiar with this part of the code.

**Review by teogeb — APPROVED** [review]
Would we like to add a similar check to `updateStream()`? 

That way we'd guarantee that if you use client to write something to the the contract registry, the operation is completed once it's propagated to The Graph. The definition of "completeness" would be consistent in that sense.

**Comment by harbu** [comment]
> That way we'd guarantee that if you use client to write something to the the contract registry, the operation is completed once it's propagated to The Graph. The definition of "completeness" would be consistent in that sense.

I wonder if it would be useful in general to abide by a principle in the client that whenever we do an operation / transaction, we consider it "completed" only once it shows up in The Graph?

**Comment by samt1803** [comment]
There is this ticket to make all transactions configurable (or global config) to wait for being mined or wait for graph-sync. 
https://linear.app/streamr/issue/NET-606/configurable-wait-parameters-for-transaction-generating-call-on-client
To mitigate the user creating this error the default could be the graph-synced state.
Or we could just always wait for theGraph to minimize errors.

**Comment by harbu** [comment]
Yeah let's think about solving this in general in another ticket. I think this one is good to go, so feel free to merge at your convenience!

**Pull request merged**
