### PR TITLE
Fix broken browser tests

### PR DESCRIPTION
**Pull request by juslesan**
- Replace Jest functions that do not work in the browser tests

### CODE REVIEW

**Comment by teogeb** [comment]
Would it be possible to modify the browser test setup so that it supports `jest-extended`? 

Currently we set the standard jest object to global namespace in `karma-setup.js`:
```
window.jest = jest
```

We also set some additional methods there, e.g.:
```
jest.advanceTimersByTime = timers.advanceTimersByTime
```

Maybe the `jest-extended` methods could be injected to global namespace similarly?

**Comment by juslesan** [comment]
> Would it be possible to modify the browser test setup so that it supports `jest-extended`?
> 
> Currently we set the standard jest object to global namespace in `karma-setup.js`:
> 
> ```
> window.jest = jest
> ```
> 
> We also set some additional methods there, e.g.:
> 
> ```
> jest.advanceTimersByTime = timers.advanceTimersByTime
> ```
> 
> Maybe the `jest-extended` methods could be injected to global namespace similarly?

I've tried to add the `jest-extended` functions to the browser tests but importing the matchers seems to not be compatible with browser. Simply importing the package to `karma-setup.js` results in weird undefined errors that seem to be caused by webpack. @teogeb

**Review by timoxley — APPROVED** [review]
👍

**Review by teogeb — APPROVED** [review]
Yes, good to get the tests green. Let's integrate `jest-extended` in another PR (or add the similar helper methods manually).

**Pull request merged**
